=== pypi-data/pypi-mirror-156/packages/sdxdatamodel/sdxdatamodel-0.0.1.tar.gz/sdxdatamodel-0.0.1/schemas/Connection.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Connection",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "class": {
            "type": "integer",
            "minimum": 0,
            "maximum": 7
        },
        "ingress_port": {
            "$ref": "Port"
        },
        "egress_port": {
            "$ref": "Port"
        },
        "end_time": {
            "type": "string",
            "format": "date-time"
        },
        "start_time": {
            "type": "string",
            "format": "date-time"
        },
        "multi_path": {
            "type": "boolean"
        },
        "preempt": {
            "type": "boolean"
        },
        "backup_path_type": {
            "type": "string",
            "enum": [
                "0",
                "1",
                "2",
                "3"
            ]
        },
        "exclusive_links": {
            "type": "array",
            "items": [
                {
                    "$ref": "Link"
                }
            ]
        },
        "inclusive_links": {
            "type": "array",
            "items": {
                "$ref": "Link"
            }
        },
        "bandwidth_required": {
            "type": "number",
            "minimum": 1,
            "maximum": 1000000
        },
        "bandwidth_measured": {
            "type": "number",
            "minimum": 1,
            "maximum": 1000000
        },
        "latency_required": {
            "type": "number",
            "minimum": 1,
            "maximum": 1000000
        },
        "latency_measured": {
            "type": "number",
            "minimum": 1,
            "maximum": 1000000
        },
        "packetloss_required": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
        },
        "packetloss_measured": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
        },
        "availability_required": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
        },
        "availability_measured": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
        },
        "paths": {
            "type": "array",
            "items": [
                {
                    "$ref": "Path"
                }
            ]
        },
        "status": {
            "type": "string",
            "enum": [
                "up",
                "down",
                "error"
            ]
        }
    },
    "required": ["id", "name", "ingress_port", "egress_port"]
}

=== pypi-data/pypi-mirror-156/packages/sdxdatamodel/sdxdatamodel-0.0.1.tar.gz/sdxdatamodel-0.0.1/tests/data/test_request.json
{
    "id": "id",
    "name": "AMLight",
    "start_time": "2000-01-23T04:56:07.000Z",
    "end_time": "2000-01-23T04:56:07.000Z",
    "bandwidth_required": 100,
    "latency_required": 20,
    "egress_port":
    {
        "id": "urn:sdx:port:amlight.net:A1:1",
        "name": "Novi100:1"
    },
    "ingress_port":
    {
        "id": "urn:ogf:network:sdx:port:zaoxi:A1:2",
        "name": "Novi100:2"
    }
}
