=== pypi-data/pypi-mirror-156/packages/sdxdatamodel/sdxdatamodel-0.0.1.tar.gz/sdxdatamodel-0.0.1/schemas/Node.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Node",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "short_name": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "location": {
            "$ref": "location.json"
        },
        "ports": {
            "type": "array",
            "items": [
                {
                    "$ref": "port.json"
                }
            ]
        }
    },
    "required": ["id", "location", "name", "ports"]
}

=== pypi-data/pypi-mirror-156/packages/sdxdatamodel/sdxdatamodel-0.0.1.tar.gz/sdxdatamodel-0.0.1/tests/data/node.json
{
    "id": "id",
    "location": {
      "address": "Miami",
      "latitude": -28.51107891831147,
      "longitude": -79.57947854792273
    },
    "name": "urn:sdx:node:amlight.net:Novi06",
    "ports": [
      {
        "id": "id",
        "name": "urn:sdx:port:amlight.net:Novi06:9",
        "node": "urn:sdx:port:amlight.net:Novi06",
        "short_name": "9",
        "status": "up"
      },
      {
        "id": "id",
        "name": "urn:sdx:port:amlight.net:Novi06:9",
        "node": "urn:sdx:port:amlight.net:Novi06",
        "short_name": "9",
        "status": "up"
      }
    ],
    "short_name": "Novi06"
  }
